Update 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,7 +1,24 @@
-#!/usr/bin/env bash 
- # Bash script that transfers a file from our client to a server 
- if [ "$#" -lt 4]; then  
-     echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"; 
- else 
-     scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/; 
- fi 
+#!/usr/bin/env bash
+# Transfers a file from a client to a server using SCP
+
+# Check if incorrect number of arguments passed
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Extracting arguments
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key="$4"
+
+# Transfer file to the server's home directory using SCP
+scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip":~/
+
+# Check if SCP command was successful
+if [ "$?" -eq 0 ]; then
+    echo "File transferred successfully to $username@$server_ip:~/"
+else
+    echo "Error occurred while transferring the file."
+fi
